version: "3"

services:
  db:
    image: percona:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
  htmlpage:
    ports:
      - "5005:5000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - htmlpage
    ports:
      - "8080:80"